### ISSUE TITLE
I need more tastypie Rcode please

### ISSUE THREAD

**Issue by dksam** [PaoloDalena/tastypie#2]
I need more tastypie Rcode please, the pies are so nice , but would also like to see the code along with them, thanks

**Comment by PaoloDalena** [comment]
I don't think I fully understand your question. All the R code I wrote to create the package functions can be found in the [R folder](https://github.com/PaoloDalena/tastypie/tree/main/R) of this repo.  If you're interested in going into more detail, you could check out the code for some of the ggplot2 package functions I used, at the [corresponding GitHub page](https://github.com/tidyverse/ggplot2).
